---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubearchive
resources:
- https://github.com/kubearchive/kubearchive/releases/download/v0.9.0/kubearchive.yaml?timeout=90

secretGenerator:
- behavior: merge
  literals:
    - DATABASE_KIND=postgresql
    - DATABASE_PORT=5432
    - DATABASE_DB=kubearchive
    - DATABASE_USER=kubearchive
    - DATABASE_URL=postgresql.postgresql.svc.cluster.local
    - DATABASE_PASSWORD=password  # notsecret
  name: kubearchive-database-credentials
  namespace: kubearchive
  type: Opaque
