---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/knative/eventing/releases/download/knative-v1.17.1/eventing.yaml?timeout=90
- https://github.com/cert-manager/cert-manager/releases/download/v1.16.3/cert-manager.yaml?timeout=90
